import * as startupActions from "./startupData";
import * as tasks from "./tasks";
import * as editTaskForm from "./editTaskForm";
import * as filter from "./filter";
import * as hash from "./hash";
import * as viewMode from "./viewMode";
import * as user from "./user";
export * from "./actionTypes";

export const loadProperties = startupActions.loadProperties;
export const loadTasks = tasks.loadTasks;
export const createTask = tasks.createTask;
export const changeTask = tasks.changeTask;
export const deleteTask = tasks.deleteTask;
export const openForm = editTaskForm.openForm;
export const closeForm = editTaskForm.closeForm;
export const changeFilterValue = filter.changeFilterValue;
export const hashChange = hash.hashChange;
export const changeViewMode = viewMode.changeViewMode;
export const login = user.login;
export const removeUser = user.removeUser;